import Head from "next/head"
import { useState } from "react"

import Button from "../components/Button"
import Card from "../components/Card"
import Input from "../components/Input"
import { useOrder } from "../hooks/useOrder"

import type { NextPage } from "next"
import { useRouter } from "next/router"
const Home: NextPage = () => {
	const { order, isLoading, hasError } = useOrder("1")
	const router = useRouter()
	const [orderNumber, setOrderNumber] = useState<number>(1)

	const handleRouteToOrder = () => {
		if (orderNumber) {
			router.push(`/orders/${orderNumber}`)
		}
	}

	return (
		<div className='mt-24'>
			<Head>
				<title>Admiral Toolbox</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div className='prose'>
				<Card>
					<div className='mb-4'>
						<h1 className='mb-1'>Welcome to the toolbox</h1>

						<p className='m-0'>Enter your order number below to get started</p>
					</div>

					<Input
						onChange={(e) => setOrderNumber(parseInt(e.target.value))}
						placeholder='1'
						label='Order Number (1-4)'
						type={"number"}
					/>
					<Button onClick={handleRouteToOrder}>Take me to my order</Button>
				</Card>
			</div>
		</div>
	)
}

export default Home
